# Generated by Django 5.2.8 on 2025-12-02 17:50

import kitchen.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["name"],
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
            },
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                default=0, validators=[kitchen.validators.validate_years_of_experience]
            ),
        ),
    ]
